### ISSUE TITLE
When using translatable the "Add new" Button crashes

### ISSUE THREAD

**Issue by RoyalPulp** [sheadawson/silverstripe-quickaddnew#10]
Hi,
I am using Silverstripe 3.1.1 with Translatable and Quickaddnew enabled.
After pushing the "Add new" Button, the popup tries to open, but in Translatable.php the $_REQUEST is misinterpreted.

Console Output:
GET http:/.../admin/pages/edit/EditForm?locale=de_DE/field/TagObjects/AddNewFormHTML 500 (Error at line 310 of .../translatable/code/model/Translatable.php) 

Debugging in Translatable.php Line 310 shows: $locale (= $REQUEST['locale'] ) = "de_DE/field/TagObjects/AddNewFormHTML" 

I don't know where this goes wrong, seems like the problem has once been also with UserDefinedForm: https://github.com/silverstripe/silverstripe-userforms/issues/83
Same has been posted in Translatable: https://github.com/silverstripe/silverstripe-translatable/issues/90

Any Idea, where this can / should be fixed?

Hendrik

**Comment by sheadawson** [comment]
Fixed in #26
