### ISSUE TITLE
doesn't work with ListBoxField in SS 3.4

### ISSUE THREAD

**Issue by xini** [sheadawson/silverstripe-quickaddnew#38]
ListBoxField complains in https://github.com/silverstripe/silverstripe-framework/blob/3.4/forms/ListboxField.php#L138 and https://github.com/silverstripe/silverstripe-framework/blob/3.4/forms/ListboxField.php#L139 about having an object given instead of an array. I know this worked once. I can't figure out what changed. the above lines were written in 2011...

**Comment by lekoala** [comment]
closed as not relevant anymore
