### ISSUE TITLE
Silverstripe 4.0 update?

### ISSUE THREAD

**Issue by joelgrondrup** [sheadawson/silverstripe-quickaddnew#42]
Hello man.

Will there be an update for the 4.0 Silverstripe branch?

**Comment by sheadawson** [comment]
@joelgrondrup I don't have time to do it myself, I'm actually looking for a new maintainer for this module. If anyone wants to take it on please let me know :)

**Comment by joelgrondrup** [comment]
Wish I had the skills for it, it's a really great module.

**Comment by purplespider** [comment]
Is there anything like this for Silverstripe 4/5?

**Comment by lekoala** [comment]
v2 has been published, enjoy :-) feel free to submit any new issues

**Comment by joelgrondrup** [comment]
Brilliant, thanks!
